Neste JupyterNotebook, foi feito a discretização baseada em quantis nos dados númericos.

In [54]:
import seaborn as sns
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [55]:
df = pd.read_csv("dataset.csv")

In [56]:
df.head(20)

,ID-modifed,Qual a situação da MORADIA DO GRUPO FAMILIAR?,Qual o principal meio de transporte que você utiliza para vir até a Universidade?,Renda per capita,NORMALIZAÇÃO: RENDA PERCAPITA,Valor Total dos bens familiares,NORMALIZAÇÃO: VALOR TOTAL DOS BENS,Despesas per capita,Normalização : Despesas per capita
0,1,1,1,166,"0,0572019297",0,0,73,"0,04400241109"
1,2,2,2,582,"0,2005513439",0,0,155,"0,09342977697"
2,3,1,1,166,"0,0572019297",0,0,41,"0,02471368294"
3,4,2,3,205,"0,07064093728",142000,"0,2028571429",20,"0,01205545509"
4,5,2,2,0,0,0,0,100,"0,06027727547"
5,6,1,2,478,"0,1647139904",7000,"0,01",111,"0,06690777577"
6,7,3,1,867,"0,2987594762",9000,"0,01285714286",237,"0,1428571429"
7,8,2,3,318,"0,1095796003",10806,"0,01543714286",27,"0,01627486438"
8,9,2,2,1118,"0,3852515507",15000,"0,02142857143",56,"0,03375527426"
9,10,2,2,1100,"0,3790489318",17000,"0,02428571429",82,"0,04942736588"
10,11,2,3,500,"0,172294969",0,0,130,"0,07836045811"
11,12,3,1,241,"0,08304617505",0,0,310,"0,1868595539"
12,13,3,1,416,"0,1433494142",0,0,232,"0,1398432791"
13,14,1,3,318,"0,1095796003",21500,"0,03071428571",246,"0,1482820976"
14,15,3,2,364,"0,1254307374",12200,"0,01742857143",1659,1
15,16,3,2,318,"0,1095796003",0,0,187,"0,1127185051"
16,17,2,3,501,"0,1726395589",10000,"0,01428571429",150,"0,0904159132"
17,18,2,1,318,"0,1095796003",35950,"0,05135714286",160,"0,09644364075"
18,19,2,1,238,"0,08201240524",45442,"0,06491714286",79,"0,04761904762"
19,20,1,3,318,"0,1095796003",0,0,221,"0,1332127788"

In [57]:
#Removendo os dados sem normalização
df = df.drop('Renda per capita', axis=1)
df = df.drop('Valor Total dos bens familiares', axis=1)
df = df.drop('Despesas per capita', axis=1)

In [59]:
df.head()

,ID-modifed,Qual a situação da MORADIA DO GRUPO FAMILIAR?,Qual o principal meio de transporte que você utiliza para vir até a Universidade?,NORMALIZAÇÃO: RENDA PERCAPITA,NORMALIZAÇÃO: VALOR TOTAL DOS BENS,Normalização : Despesas per capita
0,1,1,1,"0,0572019297",0,"0,04400241109"
1,2,2,2,"0,2005513439",0,"0,09342977697"
2,3,1,1,"0,0572019297",0,"0,02471368294"
3,4,2,3,"0,07064093728","0,2028571429","0,01205545509"
4,5,2,2,0,0,"0,06027727547"

In [94]:
#Removendo todos os dados que não vão passar pela discretização

df2 = df.drop('ID-modifed', axis=1)
df2 = df2.drop('Qual a situação da MORADIA DO GRUPO FAMILIAR?', axis=1)
df2 = df2.drop('Qual o principal meio de transporte que você utiliza para vir até a Universidade?', axis=1)
df2 = df2.replace(',', '.', regex=True)
df2 = df2.astype(float)

In [95]:
df2.head()

,NORMALIZAÇÃO: RENDA PERCAPITA,NORMALIZAÇÃO: VALOR TOTAL DOS BENS,Normalização : Despesas per capita
0,0.057202,0.000000,0.044002
1,0.200551,0.000000,0.093430
2,0.057202,0.000000,0.024714
3,0.070641,0.202857,0.012055
4,0.000000,0.000000,0.060277

In [46]:

#Verificar se há valores NaN em cada coluna
nan_values = df2.isna().sum()

print("Valores NaN em cada coluna:")
print(nan_values)

Valores NaN em cada coluna:
NORMALIZAÇÃO: RENDA PERCAPITA         0
NORMALIZAÇÃO: VALOR TOTAL DOS BENS    0
Normalização : Despesas per capita    0
dtype: int64

In [48]:
#Verificar a frequência dos valores em cada coluna
value_1 = df2['NORMALIZAÇÃO: RENDA PERCAPITA'].value_counts()

print(f"Frequência dos valores na coluna '{'NORMALIZAÇÃO: RENDA PERCAPITA'}':")
print(value_1)

Frequência dos valores na coluna 'NORMALIZAÇÃO: RENDA PERCAPITA':
NORMALIZAÇÃO: RENDA PERCAPITA
0.000000    43
0.109580    22
0.164369    20
0.137836    19
0.172295    16
            ..
0.434183     1
0.380772     1
0.201241     1
0.158167     1
0.267057     1
Name: count, Length: 486, dtype: int64

In [49]:
value_2 = df2['NORMALIZAÇÃO: VALOR TOTAL DOS BENS'].value_counts()

print(f"Frequência dos valores na coluna '{'NORMALIZAÇÃO: VALOR TOTAL DOS BENS'}':")
print(value_2)

Frequência dos valores na coluna 'NORMALIZAÇÃO: VALOR TOTAL DOS BENS':
NORMALIZAÇÃO: VALOR TOTAL DOS BENS
0.000000    424
0.014286     14
0.017143     10
0.114286      9
0.025714      9
           ...
0.008034      1
0.246429      1
0.015184      1
0.035780      1
0.009509      1
Name: count, Length: 316, dtype: int64

In [50]:
value_3 = df2['Normalização : Despesas per capita'].value_counts()

print(f"Frequência dos valores na coluna '{'Normalização : Despesas per capita'}':")
print(value_3)

Frequência dos valores na coluna 'Normalização : Despesas per capita':
Normalização : Despesas per capita
0.000000    58
0.060277    27
0.030139    19
0.120555    16
0.048222    16
            ..
0.373719     1
0.037975     1
0.218204     1
0.006631     1
0.026522     1
Name: count, Length: 314, dtype: int64

In [96]:
#Discretização baseada em quantis
def discretize_quantile(series, num_quantiles):
    return pd.qcut(series[series !=0], q=num_quantiles, labels=False, duplicates='drop') + 1
#A discretização só vai ser feita para valores diferentes de zero


num_quantiles = 19

df2['NORMALIZAÇÃO: RENDA PERCAPITA' + ' EM CATEGORIAS'] = discretize_quantile(df2['NORMALIZAÇÃO: RENDA PERCAPITA'], num_quantiles)
df2['NORMALIZAÇÃO: VALOR TOTAL DOS BENS' + ' EM CATEGORIAS'] = discretize_quantile(df2['NORMALIZAÇÃO: VALOR TOTAL DOS BENS'], 14) #Exceção
df2['Normalização : Despesas per capita' + ' EM CATEGORIAS'] = discretize_quantile(df2['Normalização : Despesas per capita'], num_quantiles)

df2.head(50)

,NORMALIZAÇÃO: RENDA PERCAPITA,NORMALIZAÇÃO: VALOR TOTAL DOS BENS,Normalização : Despesas per capita,NORMALIZAÇÃO: RENDA PERCAPITA EM CATEGORIAS,NORMALIZAÇÃO: VALOR TOTAL DOS BENS EM CATEGORIAS,Normalização : Despesas per capita EM CATEGORIAS
0,0.057202,0.000000,0.044002,1.0,NaN,6.0
1,0.200551,0.000000,0.093430,12.0,NaN,12.0
2,0.057202,0.000000,0.024714,1.0,NaN,3.0
3,0.070641,0.202857,0.012055,2.0,13.0,1.0
4,0.000000,0.000000,0.060277,NaN,NaN,8.0
5,0.164714,0.010000,0.066908,9.0,2.0,9.0
6,0.298759,0.012857,0.142857,16.0,3.0,15.0
7,0.109580,0.015437,0.016275,4.0,4.0,2.0
8,0.385252,0.021429,0.033755,18.0,5.0,4.0
9,0.379049,0.024286,0.049427,18.0,6.0,7.0
10,0.172295,0.000000,0.078360,9.0,NaN,11.0
11,0.083046,0.000000,0.186860,3.0,NaN,17.0
12,0.143349,0.000000,0.139843,7.0,NaN,15.0
13,0.109580,0.030714,0.148282,4.0,7.0,15.0
14,0.125431,0.017429,1.000000,6.0,5.0,19.0
15,0.109580,0.000000,0.112719,4.0,NaN,14.0
16,0.172640,0.014286,0.090416,10.0,3.0,12.0
17,0.109580,0.051357,0.096444,4.0,9.0,13.0
18,0.082012,0.064917,0.047619,2.0,9.0,6.0
19,0.109580,0.000000,0.133213,4.0,NaN,15.0
20,0.164369,0.026164,0.000000,9.0,6.0,NaN
21,0.161268,0.014286,0.090416,8.0,3.0,12.0
22,0.082012,0.018571,0.030139,2.0,5.0,4.0
23,0.082012,0.097143,0.027125,2.0,10.0,3.0
24,0.082012,0.042857,0.057263,2.0,8.0,8.0
25,0.082012,0.042857,0.057263,2.0,8.0,8.0
26,0.237767,0.003571,0.039180,14.0,1.0,5.0
27,0.219159,0.000000,0.095841,13.0,NaN,13.0
28,0.109580,0.012857,0.012055,4.0,3.0,1.0
29,0.189869,0.000000,0.080169,11.0,NaN,11.0
30,0.189869,0.097857,0.091621,11.0,10.0,12.0
31,0.140248,0.000000,0.000000,7.0,NaN,NaN
32,0.219159,0.085714,0.080169,13.0,10.0,11.0
33,0.183666,0.064286,0.031947,10.0,9.0,4.0
34,0.096830,0.000000,0.013261,3.0,NaN,1.0
35,0.082012,0.064919,0.032550,2.0,9.0,4.0
36,0.137836,0.000000,0.120555,6.0,NaN,14.0
37,0.422812,0.010000,0.031947,19.0,2.0,4.0
38,0.223983,0.000000,0.045208,13.0,NaN,6.0
39,0.191247,0.004286,0.172996,11.0,1.0,16.0
40,0.263956,0.000000,0.081977,15.0,NaN,11.0
41,0.241902,0.000000,0.154310,14.0,NaN,16.0
42,0.262578,0.000000,0.000000,15.0,NaN,NaN
43,0.361819,0.019033,0.268234,18.0,5.0,18.0
44,0.369056,0.000000,0.105485,18.0,NaN,13.0
45,0.129221,0.000000,0.136227,6.0,NaN,15.0
46,0.171261,0.000000,0.030139,9.0,NaN,4.0
47,0.307374,0.128571,0.000000,17.0,11.0,NaN
48,0.168160,0.017880,0.090416,9.0,5.0,12.0
49,0.389387,0.017143,0.012055,18.0,4.0,1.0

In [91]:
max1 = df2['NORMALIZAÇÃO: RENDA PERCAPITA EM CATEGORIAS'].max()
max2 = df2['NORMALIZAÇÃO: VALOR TOTAL DOS BENS EM CATEGORIAS'].max()
max3 = df2['Normalização : Despesas per capita EM CATEGORIAS'].max()

print(max1)
print(max2)
print(max3)

19.0
4.0
19.0

In [98]:
#Fazendo a categoria para os dados que são igual a 0

df2['NORMALIZAÇÃO: RENDA PERCAPITA EM CATEGORIAS'] = df2['NORMALIZAÇÃO: RENDA PERCAPITA EM CATEGORIAS'].fillna(df2['NORMALIZAÇÃO: RENDA PERCAPITA EM CATEGORIAS'].max() + 1)
df2['NORMALIZAÇÃO: VALOR TOTAL DOS BENS EM CATEGORIAS'] = df2['NORMALIZAÇÃO: VALOR TOTAL DOS BENS EM CATEGORIAS'].fillna(df2['NORMALIZAÇÃO: VALOR TOTAL DOS BENS EM CATEGORIAS'].max() + 1)
df2['Normalização : Despesas per capita EM CATEGORIAS'] = df2['Normalização : Despesas per capita EM CATEGORIAS'].fillna(df2['Normalização : Despesas per capita EM CATEGORIAS'].max() + 1)

df2.head(50)
df2.to_excel('categorias.xlsx', index=False)

In [99]:
df2.head(50)

,NORMALIZAÇÃO: RENDA PERCAPITA,NORMALIZAÇÃO: VALOR TOTAL DOS BENS,Normalização : Despesas per capita,NORMALIZAÇÃO: RENDA PERCAPITA EM CATEGORIAS,NORMALIZAÇÃO: VALOR TOTAL DOS BENS EM CATEGORIAS,Normalização : Despesas per capita EM CATEGORIAS
0,0.057202,0.000000,0.044002,1.0,15.0,6.0
1,0.200551,0.000000,0.093430,12.0,15.0,12.0
2,0.057202,0.000000,0.024714,1.0,15.0,3.0
3,0.070641,0.202857,0.012055,2.0,13.0,1.0
4,0.000000,0.000000,0.060277,20.0,15.0,8.0
5,0.164714,0.010000,0.066908,9.0,2.0,9.0
6,0.298759,0.012857,0.142857,16.0,3.0,15.0
7,0.109580,0.015437,0.016275,4.0,4.0,2.0
8,0.385252,0.021429,0.033755,18.0,5.0,4.0
9,0.379049,0.024286,0.049427,18.0,6.0,7.0
10,0.172295,0.000000,0.078360,9.0,15.0,11.0
11,0.083046,0.000000,0.186860,3.0,15.0,17.0
12,0.143349,0.000000,0.139843,7.0,15.0,15.0
13,0.109580,0.030714,0.148282,4.0,7.0,15.0
14,0.125431,0.017429,1.000000,6.0,5.0,19.0
15,0.109580,0.000000,0.112719,4.0,15.0,14.0
16,0.172640,0.014286,0.090416,10.0,3.0,12.0
17,0.109580,0.051357,0.096444,4.0,9.0,13.0
18,0.082012,0.064917,0.047619,2.0,9.0,6.0
19,0.109580,0.000000,0.133213,4.0,15.0,15.0
20,0.164369,0.026164,0.000000,9.0,6.0,20.0
21,0.161268,0.014286,0.090416,8.0,3.0,12.0
22,0.082012,0.018571,0.030139,2.0,5.0,4.0
23,0.082012,0.097143,0.027125,2.0,10.0,3.0
24,0.082012,0.042857,0.057263,2.0,8.0,8.0
25,0.082012,0.042857,0.057263,2.0,8.0,8.0
26,0.237767,0.003571,0.039180,14.0,1.0,5.0
27,0.219159,0.000000,0.095841,13.0,15.0,13.0
28,0.109580,0.012857,0.012055,4.0,3.0,1.0
29,0.189869,0.000000,0.080169,11.0,15.0,11.0
30,0.189869,0.097857,0.091621,11.0,10.0,12.0
31,0.140248,0.000000,0.000000,7.0,15.0,20.0
32,0.219159,0.085714,0.080169,13.0,10.0,11.0
33,0.183666,0.064286,0.031947,10.0,9.0,4.0
34,0.096830,0.000000,0.013261,3.0,15.0,1.0
35,0.082012,0.064919,0.032550,2.0,9.0,4.0
36,0.137836,0.000000,0.120555,6.0,15.0,14.0
37,0.422812,0.010000,0.031947,19.0,2.0,4.0
38,0.223983,0.000000,0.045208,13.0,15.0,6.0
39,0.191247,0.004286,0.172996,11.0,1.0,16.0
40,0.263956,0.000000,0.081977,15.0,15.0,11.0
41,0.241902,0.000000,0.154310,14.0,15.0,16.0
42,0.262578,0.000000,0.000000,15.0,15.0,20.0
43,0.361819,0.019033,0.268234,18.0,5.0,18.0
44,0.369056,0.000000,0.105485,18.0,15.0,13.0
45,0.129221,0.000000,0.136227,6.0,15.0,15.0
46,0.171261,0.000000,0.030139,9.0,15.0,4.0
47,0.307374,0.128571,0.000000,17.0,11.0,20.0
48,0.168160,0.017880,0.090416,9.0,5.0,12.0
49,0.389387,0.017143,0.012055,18.0,4.0,1.0